heat_template_version: queens

# NOTE: You don't need to pass the parameter explicitly from the
# parent template, it can be specified via the parameter_defaults
# in the resource_registry instead, if you want to override the default
# and/or share values with other templates in the tree.
parameters:
  ContrailRepo:
    type: string
    default: ''
  RoleParameters:
    type: json
    description: Role Specific parameters
    default: {}
  ServiceNames:
    type: comma_delimited_list
    default: []
  deployment_actions:
    default: ['CREATE']
    type: comma_delimited_list
    description: >
      List of stack actions that will trigger any deployments in this
      templates. The actions will be an empty list of the server is in the
      toplevel DeploymentServerBlacklist parameter's value.
  server:
    type: string

description: >
  This template installs the Contrail kernel module  packages in order
  to bring vhost0 interface up. Vhost0 interface must be up before
  os-net-config takes over.

conditions:
  deployment_actions_empty:
    equals:
      - {get_param: deployment_actions}
      - []

resources:

  ContrailVrouterModuleDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      name: ContrailVrouterModuleDeployment
      server:  {get_param: server}
      config: {get_resource: ContrailVrouterModuleConfig}
      input_values:
        contrail_repo: {get_param: ContrailRepo}
      actions:
        if:
          - deployment_actions_empty
          - []
          - ['CREATE'] # Only do this on CREATE

  ContrailVrouterModuleConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: contrail_repo
      config: |
        #!/bin/bash
        export LOGFILE=/tmp/contrail_trace_full.txt
        exec > >(tee -a $LOGFILE)
        exec 2>&1
        echo "=================== $(date) ==================="
        set -xv
        contrail_repo=$contrail_repo
        mkdir /var/crashes
        chmod -R 755 /var/crashes
        ulimit -c unlimited
        echo "kernel.core_pattern = /var/crashes/core.%e.%p.%h.%t" >> /etc/sysctl.conf
        sysctl -p
        if [[ ${contrail_repo} ]]; then
        curl -o /etc/sysconfig/network-scripts/ifup-vhost ${contrail_repo}/ifup-vhost
        chmod +x /etc/sysconfig/network-scripts/ifup-vhost
          cat <<EOF > /etc/yum.repos.d/contrail.repo
        [Contrail]
        name=Contrail Repo
        baseurl=${contrail_repo}
        enabled=1
        gpgcheck=0
        protect=1
        metadata_expire=30
        EOF
          yum install -y contrail-vrouter-utils
          yumdownloader contrail-vrouter --destdir /tmp
          cd /tmp
          rpm2cpio /tmp/contrail-vrouter*.rpm | cpio -idmv
          mkdir -p /lib/modules/`uname -r`/kernel/net/contrail
          cp `find /tmp/lib/modules -name vrouter.ko |tail -1` /lib/modules/`uname -r`/kernel/net/contrail
          depmod -a
          insmod /lib/modules/`uname -r`/kernel/net/contrail/vrouter.ko
        else
          modprobe vrouter
        fi

#outputs:
#  # This means get_resource from the parent template will get the userdata, see:
#  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
#  # Note this is new-for-kilo, an alternative is returning a value then using
#  # get_attr in the parent template instead.
#  OS::stack_id:
#    value: {get_resource: userdata}
