heat_template_version: queens

description: >
  Base parameters for all Contrail Services.

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  AdminPassword:
    description: The password for the keystone admin account, used for monitoring, querying neutron etc.
    type: string
    hidden: true
  AdminTenantName:
    description: Keystone admin tenant name
    type: string
    default: 'admin'
  AdminUser:
    description: Keystone admin user name
    type: string
    default: 'admin'
  ContrailAnalyticsVIP:
    default: ''
    description: Contrail Analytics Api Virtual IP address
    type: string
  ContrailConfigVIP:
    default: ''
    description: Contrail Config Virtual IP address
    type: string
  ContrailWebuiVIP:
    default: ''
    description: Contrail Webui Virtual IP address
    type: string
  ContrailRegistry:
    default: 'opencontrailnightly'
    description: Contrail Registry
    type: string
  ContrailSettings:
    default: {}
    description: Contrail Service settings
    type: json
  ContrailImageTag:
    default: 'latest'
    description: Contrail container image tag
    type: string
  DockerContrailNodeInitImageName:
    description: image
    type: string
    default: "contrail-node-init"
  DockerContrailNodemgrImageName:
    description: image
    type: string
    default: "contrail-nodemgr"
  DockerContrailStatusImageName:
    description: image
    type: string
    default: "contrail-status"
  EnableInternalTLS:
    type: boolean
    default: false
  ContrailSslEnabled:
    description:  Flag to identify is SSL should be used in internal Contrail
                  services communications (sandesh, introspect, xmpp, ..).
    type: boolean
    default: false
  ContrailSslInsecure:
    description:  Flag to identify strict cert validation (sandesh, introspect, xmpp, ..).
    type: boolean
    default: false
  ContrailServiceCertFile:
    description: Path to the node's public certificate
    type: string
    default: ''
  ContrailServiceKeyFile:
    description: Path to server's/node's private key
    type: string
    default: ''
  ContrailCaCertFile:
    default: ''
    description: Path to CA certificate
    type: string
  ContrailCaKeyFile:
    default: ''
    description: Path to CA private key
    type: string

conditions:
  contrail_config_vip_unset: {equals : [{get_param: ContrailConfigVIP}, '']}
  contrail_analytics_vip_unset: {equals : [{get_param: ContrailAnalyticsVIP}, '']}
  contrail_webui_vip_unset: {equals : [{get_param: ContrailWebuiVIP}, '']}
  internal_tls_enabled:
    not:
      or:
        - {equals: [{get_param: EnableInternalTLS}, false]}
        - {equals: [{get_param: ContrailServiceCertFile}, '']}
  contrail_tls_enabled:
    not:
      or:
        - {equals: [{get_param: ContrailSslEnabled}, false]}
        - {equals: [{get_param: ContrailServiceCertFile}, '']}
  contrail_tls_insecure: {equals: [{get_param: ContrailSslInsecure}, true]}

resources:
  ContainersCommon:
    type: ../containers-common.yaml

outputs:
  role_data:
    description: Shared role data for the Contrail services.
    value:
      service_name: contrail_base
      contrail_registry: {get_param: ContrailRegistry}
      contrail_imagetag: {get_param: ContrailImageTag}
      contrail_nodemgr_image_name:
        list_join:
          - ''
          - - {get_param: ContrailRegistry}
            - '/'
            - {get_param: DockerContrailNodemgrImageName}
            - ':'
            - {get_param: ContrailImageTag}
      config_settings:
        map_merge:
        - contrail::admin_password: {get_param: AdminPassword}
          contrail::admin_tenant_name: {get_param: AdminTenantName}
          contrail::admin_user: {get_param: AdminUser}
          # ==
          # for compatibility with puppets: neutron_plugin.pp and heat.pp
          contrail::admin_token: ''
          contrail::auth_host: {get_param: [EndpointMap, KeystoneAdmin, host] }
          contrail::auth_port: {get_param: [EndpointMap, KeystoneAdmin, port] }
          contrail::auth_protocol: {get_param: [EndpointMap, KeystonePublic, protocol] }
          contrail::api_port: '8082'
          # ==
          contrail_settings: {get_param: ContrailSettings}
        - if:
          - contrail_config_vip_unset
          - {}
          - contrail_config_vip: {get_param: ContrailConfigVIP}
        - if:
          - contrail_webui_vip_unset
          - {}
          - contrail_webui_vip: {get_param: ContrailWebuiVIP}
        - if:
          - contrail_analytics_vip_unset
          - {}
          - contrail_analytics_vip: {get_param: ContrailAnalyticsVIP}
      contrail_base_volumes: &contrail_base_volumes
        list_concat:
          - {get_attr: [ContainersCommon, volumes]}
          - - /etc/contrail/ssl:/etc/contrail/ssl
            - /var/crashes:/var/crashes
            - /var/log/containers/contrail:/var/log/contrail
      contrail_base_env: &contrail_base_env
        list_concat:
          - if:
            - contrail_tls_enabled
            - - "XMPP_SSL_ENABLE=True"
              - "SANDESH_SSL_ENABLE=True"
              - "INTROSPECT_SSL_ENABLE=True"
              - if:
                - contrail_tls_insecure
                - 'INTROSPECT_SSL_INSECURE=True'
                - 'INTROSPECT_SSL_INSECURE=False'
              - list_join:
                  - '='
                  - - 'SERVER_CERTFILE'
                    - {get_param: ContrailServiceCertFile}
              - list_join:
                  - '='
                  - - 'SERVER_KEYFILE'
                    - {get_param: ContrailServiceKeyFile}
              - list_join:
                  - '='
                  - - 'SERVER_CA_CERTFILE'
                    - {get_param: ContrailCaCertFile}
              - list_join:
                  - '='
                  - - 'SERVER_CA_KEYFILE'
                    - {get_param: ContrailCaKeyFile}
            - []
          - if:
            - internal_tls_enabled
            - - "KEYSTONE_AUTH_INSECURE=False"
              - "KEYSTONE_AUTH_PROTO=https"
              - list_join:
                  - '='
                  - - 'KEYSTONE_AUTH_CERTFILE'
                    - {get_param: ContrailServiceCertFile}
              - list_join:
                  - '='
                  - - 'KEYSTONE_AUTH_KEYFILE'
                    - {get_param: ContrailServiceKeyFile}
            - []
      docker_config:
        step_2:
          contrail_node_init:
            image:
              list_join:
                - ''
                - - {get_param: ContrailRegistry}
                  - '/'
                  - {get_param: DockerContrailNodeInitImageName}
                  - ':'
                  - {get_param: ContrailImageTag}
            environment:
              list_concat:
                - *contrail_base_env
                - - list_join:
                      - ''
                      - - 'CONTRAIL_STATUS_IMAGE='
                        - {get_param: ContrailRegistry}
                        - '/'
                        - {get_param: DockerContrailStatusImageName}
                        - ':'
                        - {get_param: ContrailImageTag}
            net: host
            pid: host
            privileged: true
            user: root
            volumes:
              list_concat:
                - *contrail_base_volumes
                - - /usr/bin:/host/usr/bin
