heat_template_version: ocata

description: >
  Parameters for Contrail Container based deployment.

parameters:
  ContrailAnalyticsDBPassword:
    description:  The password for Contrail Analytics DB.
                  Change the password for production.
    type: string
    default: 'c0ntrail123'
    hidden: true
  ContrailAnalyticsDBUser:
    description: The password for Contrail Analytics DB
    type: string
    default: 'contrail_analyticsdb_cassandra_user'
  ContrailConfigDBPassword:
    description:  The password for Contrail Config DB.
                  Change the password for production.
    type: string
    default: 'c0ntrail123'
    hidden: true
  ContrailConfigDBUser:
    description: The password for Contrail Config DB
    type: string
    default: 'contrail_configdb_cassandra_user'
  ContrailContainerTag:
    description: Container tag to identify containers to be used.
    type: string
    default: '4.0.1.0-25'
  ContrailContainerUrl:
    description: Url for containers downloading, if not set then ContrailRepo will be used.
    type: string
    default: ''
  ContrailExternalCassandraServers:
    description:  List of external servers to be used instead of internally
                  deployed in contrail controller container. If provided the
                  services will not be deployed in contrail controller container.
    type: comma_delimited_list
    default: []
  ContrailExternalLB:
    description:  Flag to identify the whether the loadbalancer is internaly
                  hosted in the lb container or managed externally.
                  Based on which the listen port of the contrail-api will be decided.
    type: boolean
    default: false
  ContrailExternalRabbitmqServers:
    description:  List of external servers to be used instead of internally
                  deployed in contrail controller container. If provided the
                  services will not be deployed in contrail controller container.
    type: comma_delimited_list
    default: []
  ContrailExternalZookeeperServers:
    description:  List of external servers to be used instead of internally
                  deployed in contrail controller container. If provided the
                  services will not be deployed in contrail controller container.
    type: comma_delimited_list
    default: []
  ContrailSslEnabled:
    description:  Flag to identify is SSL should be used in internal Contrail
                  services communications (sandesh, introspect, xmpp, ..).
    type: boolean
    default: false

conditions:
  contrail_container_url_unset: {equals : [{get_param: ContrailContainerUrl}, []]}
  contrail_external_cassandra_servers_unset: {equals : [{get_param: ContrailExternalCassandraServers}, []]}
  contrail_external_rabbitmq_servers_unset: {equals : [{get_param: ContrailExternalRabbitmqServers}, []]}
  contrail_external_zookeeper_servers_unset: {equals : [{get_param: ContrailExternalZookeeperServers}, []]}

outputs:
  role_data:
    description: Shared data for Contrail container based deployment.
    value:
      service_name: contrail_container
      config_settings:
        map_merge:
        - contrail_analyticsdb_cassandra_password: {get_param: ContrailAnalyticsDBPassword}
          contrail_analyticsdb_cassandra_user: {get_param: ContrailAnalyticsDBUser}
          contrail_configdb_cassandra_password: {get_param: ContrailConfigDBPassword}
          contrail_configdb_cassandra_user: {get_param: ContrailConfigDBUser}
          contrail::container::tag: {get_param: ContrailContainerTag}
          contrail_ssl_enabled: {get_param: ContrailSslEnabled}
          contrail::external_lb: {get_param: ContrailExternalLB}
        - if:
          - contrail_container_url_unset
          - {}
          - contrail::container::url: {get_param: ContrailContainerUrl}
        - if:
          - contrail_external_cassandra_servers_unset
          - {}
          - contrail::external_cassandra_servers: {get_param: ContrailExternalCassandraServers}
        - if:
          - contrail_external_rabbitmq_servers_unset
          - {}
          - contrail::external_rabbitmq_servers: {get_param: ContrailExternalRabbitmqServers}
        - if:
          - contrail_external_zookeeper_servers_unset
          - {}
          - contrail::external_zookeeper_servers: {get_param: ContrailExternalZookeeperServers}
